// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxNrIgDaR0aYuHumdyRWRVBXNgm9JI5Gc',
    appId: '1:705732616836:web:1503e1cfad54b52b8618d1',
    messagingSenderId: '705732616836',
    projectId: 'budget-manager-15f81',
    authDomain: 'budget-manager-15f81.firebaseapp.com',
    storageBucket: 'budget-manager-15f81.firebasestorage.app',
    measurementId: 'G-D139B0B4N3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd1R7Fyu1VKhOJpR-itn51UjcClE0SPCg',
    appId: '1:705732616836:android:e47ec498526b47138618d1',
    messagingSenderId: '705732616836',
    projectId: 'budget-manager-15f81',
    storageBucket: 'budget-manager-15f81.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1lVf0J8K6wkXuxHRqU4ZWely_R8uLr3Q',
    appId: '1:705732616836:ios:9ff12d0e5de4721b8618d1',
    messagingSenderId: '705732616836',
    projectId: 'budget-manager-15f81',
    storageBucket: 'budget-manager-15f81.firebasestorage.app',
    androidClientId: '705732616836-0ild6ep5qv1qa3b2und53c7hb5dc6su6.apps.googleusercontent.com',
    iosClientId: '705732616836-hofbdnch2cbmbiu5scapv47rrhk2aqnq.apps.googleusercontent.com',
    iosBundleId: 'com.ninjageeksco.budgetManager',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1lVf0J8K6wkXuxHRqU4ZWely_R8uLr3Q',
    appId: '1:705732616836:ios:9ff12d0e5de4721b8618d1',
    messagingSenderId: '705732616836',
    projectId: 'budget-manager-15f81',
    storageBucket: 'budget-manager-15f81.firebasestorage.app',
    androidClientId: '705732616836-0ild6ep5qv1qa3b2und53c7hb5dc6su6.apps.googleusercontent.com',
    iosClientId: '705732616836-hofbdnch2cbmbiu5scapv47rrhk2aqnq.apps.googleusercontent.com',
    iosBundleId: 'com.ninjageeksco.budgetManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxNrIgDaR0aYuHumdyRWRVBXNgm9JI5Gc',
    appId: '1:705732616836:web:8c74058929937e598618d1',
    messagingSenderId: '705732616836',
    projectId: 'budget-manager-15f81',
    authDomain: 'budget-manager-15f81.firebaseapp.com',
    storageBucket: 'budget-manager-15f81.firebasestorage.app',
    measurementId: 'G-M53X6YNSGP',
  );

}